"""empty message

Revision ID: eaefabfc4a8e
Revises: 
Create Date: 2024-07-27 02:27:43.261290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaefabfc4a8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    op.drop_table('Customer')
    op.alter_column('answer', 'content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('question', 'subject',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('question', 'content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_question_id', table_name='question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_question_id', 'question', ['id'], unique=False)
    op.alter_column('question', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('question', 'subject',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
    op.alter_column('answer', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.create_table('Customer',
    sa.Column('custid', mysql.INTEGER(display_width=2), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('custid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Book',
    sa.Column('bookid', mysql.INTEGER(display_width=2), autoincrement=False, nullable=False),
    sa.Column('bookname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('publisher', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bookid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
